export {Account} from './account/account';
export {Categories} from './categories/categories';
export {Nav} from './nav/nav';
export {List} from './footerList/listFooter';
export {CopyRight} from './copyRight/copyRight';
export {AboutUs} from './footerAboutUs/footerAboutUs'
export {Contact} from './footerContact/contactFooter';
export {Help} from './footerHelp/footerHelp';
export {Policy} from './footerPolicy/footerPolicy';
export {Subscribe} from './footerSubscribe/footerSubscribe';
export {Banner} from './banner/banner';
export {Carousel} from './carousel/carousel';
export {BestSeller} from './bestSeller/bestSeller';
export {DealOfDay} from './dealOfDay/dealOFDay';
export {RecomendetProduct} from './recomendetProduct/recomendetProduct'
export {SlideBanner} from './slideBanner/slideBanner';
export {LoginForm} from './loginForm/loginForm';
export {CreateAccount} from './createAccount/createAccount';
export {Modal} from './modal/modal';
export {Filter} from './filter/filter';
export {ProductCart} from './productCart/productCart';
export {ProductDataPage} from './productDataPage/productDataPage';
export {ProductSecurity} from './productSecurity/productSecurity';
export {OrderProduct} from './orderProduct/orderProduct';
export {ContactForm} from './contactForm/contactForm';
export {RegisterForm} from './registerForm/registerForm';
export {AdressContainer} from './adressContainer/adressContainer'
export {Map} from './map/map';
export {Galery} from './galery/galery';
export {WhyUs} from './whyUs/whyUs';
export {GalerySlider} from './galerySlider/galerySlider'; 
export {AccountFilter} from './accountFilter/accountFilter';
export {PersonalData} from './personalData/personalData';
export {Carousell} from './carousell/carousell';
export {Brands} from './brands/brands';